name: Publish image
description: Publishes a Docker image
inputs:
  app_name:
    required: true
    description: Application name
  app_version:
    required: true
    description: Application version
  tag_name:
    required: true
    description: Docker tag

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: app_image
        path: tmp/app_image
    - run: task docker:load
      shell: sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        APP_VERSION: ${{ inputs.app_version }}
    - run: task docker:push
      shell: sh
      env:
        APP_NAME: ${{ inputs.app_name }}
        APP_VERSION: ${{ inputs.tag_name }}
