name: Build a Docker image
description: Builds a Docker image
inputs:
  app_name:
    required: true
    description: Application name
  app_version:
    required: true
    description: Application version
  dockerfile:
    required: true
    description: Path to the Dockerfile
  registry_host:
    required: false
    description: Registry hostname
  registry_user:
    required: true
    description: Registry username
  tag_name:
    required: true
    description: Docker tag

runs:
  using: composite
  steps:
    - shell: sh
      run: docker build --no-cache --build-arg ARCH=amd64 -t ${{ inputs.app_name }}:${{ inputs.app_version }} -f ${{ inputs.dockerfile }} .
    - shell: sh
      run: docker tag ${{ inputs.app_name }}:${{ inputs.app_version }} ${{ inputs.registry_host }}/${{ inputs.registry_user }}/${{ inputs.app_name }}:${{ inputs.tag_name }}
    - shell: sh
      run: docker push ${{ inputs.registry_host }}/${{ inputs.registry_user }}/${{ inputs.app_name }}:${{ inputs.tag_name }}