name: Build a Docker image
description: Builds a Docker image
inputs:
  app_name:
    required: true
    description: Application name
  dockerfile:
    required: true
    description: Path to the Dockerfile
  registry_host:
    required: false
    description: Registry hostname
  registry_user:
    required: true
    description: Registry username

runs:
  using: composite
  steps:
    - shell: bash
      run: docker build --no-cache --build-arg ARCH=amd64 -t ${{ inputs.app_name }}:${{ github.sha }} -f ${{ inputs.dockerfile }} .
    - shell: bash
      run: |
        IMG_BASE_NAME="${{ inputs.registry_user }}/${{ inputs.app_name }}"
        if [ ! -z "${{ inputs.registry_host }}" ]; then
          IMG_BASE_NAME="${{ inputs.registry_host }}/${{ inputs.registry_user }}/${{ inputs.app_name }}"
        fi
        echo "IMG_BASE_NAME=${IMG_BASE_NAME}" >> ${{ github.env }}
        echo "SHA_SHORT=$(git rev-parse --short "${{ github.sha }}")" >> ${{ github.env }}
    - shell: bash
      run: |
        docker tag ${{ inputs.app_name }}:${{ github.sha }} ${{ env.IMG_BASE_NAME }}:${{ github.sha }}
        docker tag ${{ inputs.app_name }}:${{ github.sha }} ${{ env.IMG_BASE_NAME }}:${{ env.SHA_SHORT }}
        docker tag ${{ inputs.app_name }}:${{ github.sha }} ${{ env.IMG_BASE_NAME }}:${{ github.ref_name }}
        if [ "${{ github.ref_name }}" == "main" ] || [ "${{ github.ref_name }}" == "master" ] ; then
          docker tag ${{ inputs.app_name }}:${{ github.sha }} ${{ env.IMG_BASE_NAME }}:latest
        fi
    - shell: bash
      run: |
        docker push ${{ env.IMG_BASE_NAME }}:${{ github.sha }}
        docker push ${{ env.IMG_BASE_NAME }}:${{ env.SHA_SHORT }}
        docker push ${{ env.IMG_BASE_NAME }}:${{ github.ref_name }}
        if [ "${{ github.ref_name }}" == "main" ] || [ "${{ github.ref_name }}" == "master" ] ; then
          docker push ${{ env.IMG_BASE_NAME }}:latest
        fi
