name: Build a Docker image
description: Builds a Docker image
inputs:
  app_name:
    required: true
    description: Application name
  app_version:
    required: true
    description: Application version
  dockerfile:
    required: true
    description: Path to Dockerfile

runs:
  using: composite
  steps:
    - shell: sh
      run: docker build --no-cache --build-arg ARCH=amd64 -t ${{ inputs.app_name }}:${{ inputs.app_version }} -f ${{ inputs.dockerfile }} .
    - shell: sh
      run: |
        mkdir -p tmp/app_image
        docker save -o tmp/app_image/${{ inputs.app_name }}_${{ inputs.app_version }}.tar ${{ inputs.app_name }}:${{ inputs.app_version }}
    - uses: actions/upload-artifact@v3
      with:
        name: app_image
        path: tmp/app_image/
        retention-days: 7
