name: Build a Docker image
description: Builds a Docker image
inputs:
  app_name:
    required: true
    description: Application name
  app_version:
    required: true
    description: Application version

runs:
  using: composite
  steps:
    - run: task docker:build
      shell: sh
      env:
        TASK_APP_NAME: ${{ inputs.app_name }}
        TASK_APP_VERSION: ${{ inputs.app_version }}
    - run: task docker:save
      shell: sh
      env:
        TASK_APP_NAME: ${{ inputs.app_name }}
        TASK_APP_VERSION: ${{ inputs.app_version }}
    - uses: actions/upload-artifact@v3
      with:
        name: app_image
        path: tmp/app_image/
        retention-days: 1
