name: Build
description: Publishes a Docker image
inputs:
  app_name:
    required: true
    description: Application name
  app_version:
    required: true
    description: Application version

runs:
  using: composite
  steps:
    - uses: ashep/go-ci-github/actions/prepare@main
    - uses: actions/download-artifact@v3
      with:
        name: tmp
    - run: task docker:load
      shell: sh
      env:
        TASK_APP_NAME: ${{ inputs.app_name }}
        TASK_APP_VERSION: ${{ inputs.app_version }}
    - run: task docker:push
      shell: sh
      env:
        TASK_APP_NAME: ${{ inputs.app_name }}
        TASK_APP_VERSION: ${{ inputs.app_version }}
