name: Go private
description: Setup access to go private modules

inputs:
  ci_private_key:
    required: false
    description: CI private key
  go_private:
    required: false
    description: Go private modules list

runs:
  using: composite
  steps:
    - shell: sh
      if: ${{ inputs.go_private != '' && inputs.ci_private_key != '' }}
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        (cat <<EOF
        Host github.com
            StrictHostKeyChecking no
        EOF
        ) > ~/.ssh/config
        (cat <<EOF
        ${{ inputs.ci_private_key }}
        EOF
        ) > ci.key
        chmod 0600 ci.key
        ssh-add ci.key
        git config --global url."ssh://git@github.com".insteadOf "https://github.com"
        go env -w GOPRIVATE="${{ inputs.go_private }}"
