name: Go private
description: Setup access to go private modules

inputs:
  private_key:
    description: CI private key
  go_private:
    description: Go private modules list

runs:
  using: composite
  steps:
    - shell: sh
      if: ${{ inputs.go_private != '' && inputs.private_key != '' }}
      run: |
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        (cat <<EOF
        Host github.com
            StrictHostKeyChecking no
        EOF
        ) > ~/.ssh/config
        (cat <<EOF
        ${{ inputs.private_key }}
        EOF
        ) > ~/.ssh/id_rsa
        chmod 0600 ~/.ssh/id_rsa
        ssh-add ~/.ssh/id_rsa
        git config --global url."ssh://git@github.com".insteadOf "https://github.com"
        go env -w GOPRIVATE="${{ inputs.go_private }}"
