name: Setup Taskfile
description: Setups Taskfile runner

inputs:
  version:
    description: golanci-lint version to install
    required: true

runs:
  using: composite
  steps:
    - run: mkdir -p bin
      shell: sh
    - run: echo "$(pwd)/bin" >> $GITHUB_PATH
      shell: sh
    - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v${{ inputs.version }}
      shell: sh
