name: Setup Taskfile
description: Setups Taskfile runner
runs:
  using: composite
  steps:
    - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
      shell: sh
    - run: go mod vendor
      shell: sh
    - run: task init
      shell: sh
