name: Setup Taskfile
description: Setups Taskfile runner
runs:
  using: composite
  steps:
    - run: if [ -z "$(go env GOPATH)" ]; then echo "go is not installed"; exit 1; fi
      shell: sh
    - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
      shell: sh
    - run: ls -l $(go env GOPATH)/bin
      shell: sh
