version: "3"

tasks:
  run:
    desc: Run the application
    env:
      APP_CONFIG_PATH:
        sh: if [ -f "config.yaml" ]; then echo config.yaml; fi
    cmds:
      - go run -race main.go {{.CLI_ARGS}}

  gen:
    desc: Generate go code
    cmds:
      - go generate -v ./...

  gen-proto:
    desc: Generate protobuf code
    cmds:
      - rm -rvf ./sdk/proto
      - buf lint proto
      - buf generate

  build:
    desc: Build the application
    env:
      CGO_ENABLED: "0"
    cmds:
      - if [ -z "{{.APP_NAME}}" ]; then echo "APP_NAME var is not set"; exit 1; fi
      - if [ -z "{{.APP_VERSION}}" ]; then echo "APP_VERSION var is not set"; exit 1; fi
      - mkdir -p build
      - go mod vendor
      - go build -ldflags="-X 'github.com/ashep/go-apprun.appName={{.APP_NAME}}' -X 'github.com/ashep/go-apprun.appVer={{.APP_VERSION}}'" -o build/app main.go

  migrate-up:
    desc: Apply DB migrations
    env:
      APP_CONFIG_PATH:
        sh: '[ -f "config.yaml" ] && echo config.yaml'
    cmds:
      - go run main.go -migrate-up {{.CLI_ARGS}}

  migrate-down:
    desc: Revert DB migrations
    env:
      APP_CONFIG_PATH:
        sh: '[ -f "config.yaml" ] && echo config.yaml'
    cmds:
      - go run main.go -migrate-down {{.CLI_ARGS}}

  vet:
    desc: Run 'go vet'
    cmds:
      - go vet ./...

  staticcheck:
    desc: Run staticcheck
    cmds:
      - if ! which -s staticcheck; then go install honnef.co/go/tools/cmd/staticcheck@latest; fi
      - staticcheck ./...

  golangci-lint:
    desc: Run golangci-lint linter
    cmds:
      - if ! which -s golangci-lint; then brew install golangci-lint; fi
      - golangci-lint run ./...

  govulncheck:
    desc: Run govulncheck
    cmds:
      - if ! which -s govulncheck; then go install golang.org/x/vuln/cmd/govulncheck@latest; fi
      - govulncheck ./...

  lint:
    desc: Run all checkers and linters
    cmds:
      - task: vet
      - task: staticcheck
      - task: golangci-lint
      - task: govulncheck

  unit-test:
    desc: Run unit tests
    vars:
      GOTEST:
        sh: which gotest || echo go test
    cmds:
      - '{{.GOTEST}} -v -mod=vendor -race -failfast {{default "./..." .CLI_ARGS}}'

  func-test:
    desc: Run functional tests
    vars:
      GOTEST:
        sh: which gotest || echo go test
    cmds:
      - if [ -z "{{.APP_NAME}}" ]; then echo "APP_NAME var is not set"; exit 1; fi
      - if [ -f docker-compose.tests.yaml ]; then docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml up --remove-orphans -d; fi
      - if [ -f docker-compose.tests.yaml ]; then docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml run --rm --remove-orphans tests go test -v -mod=vendor -tags=functest ./tests/...; fi

  func-test:manual:
    desc: Attach to functional tests container
    cmds:
      - if [ -z "{{.APP_NAME}}" ]; then echo "APP_NAME var is not set"; exit 1; fi
      - if [ -f docker-compose.tests.yaml ]; then docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml up --remove-orphans -d; fi
      - if [ -f docker-compose.tests.yaml ]; then docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml run --rm -i tests sh; fi

  func-test:clean:
    desc: Cleanup test environment
    cmds:
      - if [ -z "{{.APP_NAME}}" ]; then echo "APP_NAME var is not set"; exit 1; fi
      - if [ -f docker-compose.tests.yaml ]; then docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml down --remove-orphans; fi
      - if [ -f docker-compose.tests.yaml ]; then docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml down -v; fi
