name: Publish image
description: Publishes a Docker image
inputs:
  app_name:
    required: true
    description: Application name
  app_version:
    required: true
    description: Application version
  registry_host:
    required: false
    description: Registry hostname
  registry_user:
    required: true
    description: Registry username
  tag_name:
    required: true
    description: Docker tag

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: app_image
        path: tmp/app_image
    - shell: sh
      run: docker load -i tmp/app_image/${{ inputs.app_name }}_${{ inputs.app_version }}.tar
    - shell: sh
      run: |
        docker tag ${{ inputs.app_name }}:${{ inputs.app_version }} ${{ inputs.registry_host }}/${{ inputs.registry_user }}/${{ inputs.app_name }}:${{ inputs.tag_name }}
        docker push ${{ inputs.registry_host }}/${{ inputs.registry_user }}/${{ inputs.app_name }}:${{ inputs.tag_name }}
