name: build-go-app
on:
  workflow_call:
    inputs:
      registry_user:
        required: false
        type: string
    secrets:
      registry_password:
        required: false

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: ashep/go-ci/actions/prepare@main
      - run: task lint:golangci

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ashep/go-ci/actions/prepare@main
      - run: task test:unit

  func-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ashep/go-ci/actions/prepare@main
      - run: task test:func

  build:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - func-tests
    steps:
      - uses: ashep/go-ci/actions/prepare@main
      - uses: ashep/go-ci/actions/build@main
        if: ${{ github.ref_name }} == 'main'
        with:
          app_name: ${{ github.event.repository.name }}
          app_version: latest
      - uses: ashep/go-ci/actions/build@main
        if: ${{ github.ref_name }} != 'main'
        with:
          app_name: ${{ github.event.repository.name }}
          app_version: dev

  publish:
    runs-on: ubuntu-latest
    if: ${{ inputs.registry_user }} != "" && ${{ secrets.registry_password }} != ""
    needs:
      - build
    env:
      TASK_APP_NAME: ${{ github.event.repository.name }}
      TASK_APP_VERSION: ${{ github.ref_name }}
    steps:
      - run: docker login -u ${{ inputs.registry_user }} -p ${{ secrets.registry_password }}
      - uses: ashep/go-ci/actions/prepare@main
      - uses: ashep/go-ci/actions/publish@main
        if: ${{ github.ref_name }} == 'main'
        with:
          app_name: ${{ github.event.repository.name }}
          app_version: latest
      - uses: ashep/go-ci/actions/publish@main
        if: ${{ github.ref_name }} != 'main'
        with:
          app_name: ${{ github.event.repository.name }}
          app_version: dev
