name: build-go-app
on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
      app_version:
        type: string
        required: true
      dockerfile:
        type: string
        required: true
      go_private:
        type: string
        required: false
      registry_host:
        type: string
        required: false
      registry_user:
        type: string
        required: false
    secrets:
      private_key:
        required: false
      registry_password:
        required: false

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: ashep/go-ci/actions/setup-golangci-lint@v1
      - run: golangci-lint run ./...

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: ashep/go-ci/actions/go-private@v1
        with:
          private_key: ${{ secrets.private_key }}
          go_private: ${{ inputs.go_private }}
      - run: go mod vendor
      - run: go test -v -mod=vendor -race ./...

  func-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: ashep/go-ci/actions/go-private@v1
        with:
          private_key: ${{ secrets.private_key }}
          go_private: ${{ inputs.go_private }}
      - run: go mod vendor
      - run: |
          if [ -f docker-compose.tests.yaml ];
            then docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml up --remove-orphans -d
            docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml run --rm --remove-orphans tests go test -v -mod=vendor -tags=functest ./tests/...
          fi

  build-image:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - func-tests
    steps:
      - uses: actions/checkout@v3
      - uses: ashep/ci/actions/build-image@v1
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}
          dockerfile: ${{ inputs.dockerfile }}

  push-image:
    runs-on: ubuntu-latest
    if: ${{ inputs.registry_user != '' }}
    needs:
      - build-image
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry_host }}
          username: ${{ inputs.registry_user }}
          password: ${{ secrets.registry_password }}
      - uses: actions/checkout@v3
      - uses: ashep/go-ci/actions/push-image@v1
        if: github.ref_name == 'main'
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}
          registry_host: ${{ inputs.registry_host }}
          registry_user: ${{ inputs.registry_user }}
          tag_name: latest
      - uses: ashep/go-ci/actions/push-image@v1
        if: github.ref_name != 'main'
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}
          registry_host: ${{ inputs.registry_host }}
          registry_user: ${{ inputs.registry_user }}
          tag_name: dev
      - uses: ashep/go-ci/actions/push-image@v1
        if: github.ref_type == 'tag'
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}
          registry_host: ${{ inputs.registry_host }}
          registry_user: ${{ inputs.registry_user }}
          tag_name: ${{ github.ref_name }}
