name: build-go-lib
on: workflow_call
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - uses: ashep/go-ci/actions/setup-golangci-lint@v1
      - run: task init
      - run: task lint:golangci

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v1
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.21'
      - run: go mod vendor
      - run: task init
      - run: task test:unit
