name: deploy-docker
on:
  workflow_call:
    inputs:
      compose_filename:
        type: string
        required: false
        default: docker-compose.yaml
    secrets:
      docker_host:
        required: true
      private_key:
        required: true
      env:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env variables
        if: ${{ secrets.env }}
        run: |
          (cat <<EOF
          ${{ secrets.env }}
          EOF
          ) > .env
      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          (cat <<EOF
          ${{ secrets.private_key }}
          EOF
          ) > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

          docker context create remote --docker "host=${{ secrets.docker_host }}"
          docker --context remote compose -f ${{ inputs.compose_filename }}
