name: deploy-helm
on:
  workflow_call:
    inputs:
      release:
        type: string
        required: true
      chart:
        type: string
        required: true
      namespace:
        type: string
        required: true
    secrets:
      kubeconfig:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create kubeconfig
        run: | 
          mkdir -p ~/.kube
          (cat <<EOF
          ${{ secrets.kubeconfig }}
          EOF
          ) > ~/.kube/config
          chmod 0600 ~/.kube/config
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - run: task init
      - name: Deploy # TODO: move this to taskfile
        run: helm upgrade -n ${{ inputs.namespace }} --install --create-namespace ${{ inputs.release }} ${{ inputs.chart }}
