name: deploy-docker
on:
  workflow_call:
    inputs:
      compose_filename:
        type: string
        required: false
        default: docker-compose.yaml
      ssh_port:
        type: string
        required: false
        default: "22"

    secrets:
      ssh_host:
        required: true
      ssh_user:
        required: true
      ssh_key:
        required: true
      env:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env variables
        env: # https://stackoverflow.com/questions/72925899/github-actions-detect-if-secret-exists
          dotenv: ${{ secrets.env }}
        if: ${{ env.dotenv != '' }}
        run: |
          (cat <<EOF
          ${{ secrets.env }}
          EOF
          ) > .env
      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          
          #          (cat <<EOF
          #          Host *
          #            StrictHostKeyChecking no
          #            HostKeyAlgorithms +ssh-rsa,ssh-dss
          #            PubkeyAcceptedKeyTypes +ssh-rsa,ssh-dss
          #          EOF
          #          ) > ~/.ssh/config

          (cat <<EOF
          ${{ secrets.ssh_key }}
          EOF
          ) > ssh_id
          chmod 0600 ssh_id
          
          eval $(ssh-agent -s)
          ssh-keyscan -H -p ${{ inputs.ssh_port }} ${{ secrets.ssh_host }} > ~/.ssh/known_hosts
          ssh-add ssh_id
  
          docker context create remote --docker "host=ssh://${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:${{ inputs.ssh_port }}"
          docker --context remote compose -f ${{ inputs.compose_filename }} up -d --always-recreate-deps --force-recreate
