name: deploy-helm
on:
  workflow_call:
    inputs:
      chart:
        type: string
        required: false
        default: ./helm
      repository:
        type: string
        required: false
      namespace:
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      namespace_suffix:
        type: string
        required: false
      release:
        type: string
        required: false
        default: ${{ github.event.repository.name }}
    secrets:
      kubeconfig:
        required: true
      values:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create kubeconfig
        run: | 
          mkdir -p ~/.kube
          (cat <<EOF
          ${{ secrets.kubeconfig }}
          EOF
          ) > ~/.kube/config
          chmod 0600 ~/.kube/config
      - name: Setup Helm repo
        if: ${{ inputs.repository }}
        run: helm repo add ${{ inputs.repository }} && helm repo update
      - name: Prepare values
        run: |
          (cat <<EOF
          podAnnotations:
            git.ref: ${{ github.ref }}
            git.sha: ${{ github.sha }}
          EOF
          ) > values.ci.yaml
          echo -e '${{ secrets.values }}' > values.add.yaml
      - name: Deploy
        run: |
          NAMESPACE="${{ inputs.namespace }}"
          if [ ! -z "${{ inputs.namespace_suffix }}" ]; then NAMESPACE="${NAMESPACE}-${{ inputs.namespace_suffix }}"; fi
          helm upgrade -i -n ${NAMESPACE} --create-namespace -f values.add.yaml -f values.ci.yaml ${{ inputs.release }} ${{ inputs.chart }}
