name: deploy-helm
on:
  workflow_call:
    inputs:
      chart:
        type: string
        required: false
        default: ./helm
      repository:
        type: string
        required: false
      namespace:
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      namespace_suffix:
        type: string
        required: false
      release:
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      ssh_host:
        type: string
        required: false
      ssh_port:
        type: string
        required: false
        default: 22
      ssh_user:
        type: string
        required: false
      kube_port:
        type: number
        default: 6443
        required: false

    secrets:
      ssh_key:
        required: false
      kubeconfig:
        required: true
      chart_values:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create kubeconfig
        run: | 
          mkdir -p ~/.kube
          (cat <<EOF
          ${{ secrets.kubeconfig }}
          EOF
          ) > ~/.kube/config
          chmod 0600 ~/.kube/config
      - name: Setup Helm repo
        if: ${{ inputs.repository }}
        run: helm repo add ${{ inputs.repository }} && helm repo update
      - name: Prepare values
        run: |
          (cat <<EOF
          podAnnotations:
            git.ref: ${{ github.ref }}
            git.sha: ${{ github.sha }}
          EOF
          ) > values.ci.yaml
          echo -e '${{ secrets.chart_values }}' > values.add.yaml
      - name: Deploy
        run: |
          if [ -n "${{ inputs.ssh_host }}" -a -n "${{ inputs.ssh_user }}" ]; then
            mkdir -p ~/.ssh
          (cat <<EOF
          ${{ secrets.ssh_key }}
          EOF
          ) > ssh_id
            chmod 0600 ssh_id
            eval $(ssh-agent -s)
            ssh-keyscan -H -p "${{ inputs.ssh_port }}" "${{ inputs.ssh_host }}" > ~/.ssh/known_hosts
            ssh-add ssh_id
            ssh -p ${{ inputs.ssh_port }} -fNL ${{ inputs.kube_port }}:127.0.0.1:${{ inputs.kube_port }} ${{ inputs.ssh_user }}@${{ inputs.ssh_host }}
          fi
          
          NAMESPACE="${{ inputs.namespace }}"
          if [ -n "${{ inputs.namespace_suffix }}" ]; then NAMESPACE="${NAMESPACE}-${{ inputs.namespace_suffix }}"; fi
          NAMESPACE="${NAMESPACE//./-}"
          helm upgrade -i -n ${NAMESPACE} --create-namespace -f values.add.yaml -f values.ci.yaml ${{ inputs.release }} ${{ inputs.chart }}
