name: deploy-docker
on:
  workflow_call:
    inputs:
      compose_filename:
        type: string
        required: false
        default: docker-compose.yaml

    secrets:
      ssh_host:
        required: true
      ssh_port:
        required: true
      ssh_user:
        required: true
      ssh_key:
        required: true
      dotenv:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add .env variables
        run: |
          (cat <<EOF
          ${{ secrets.dotenv }}
          EOF
          ) >> .env
      - name: Deploy
        run: |
          mkdir -p ~/.ssh

          (cat <<EOF
          ${{ secrets.ssh_key }}
          EOF
          ) > ssh_id
          chmod 0600 ssh_id
          
          eval $(ssh-agent -s)
          ssh-keyscan -H -p ${{ secrets.ssh_port }} ${{ secrets.ssh_host }} > ~/.ssh/known_hosts
          ssh-add ssh_id
  
          docker context create remote --docker "host=ssh://${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:${{ secrets.ssh_port }}"
          docker --context remote compose -f ${{ inputs.compose_filename }} up -d --always-recreate-deps --force-recreate
