name: deploy-helm
on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: true
      repository:
        type: string
        required: false
      chart:
        type: string
        required: true
      release:
        type: string
        required: true
      values_path:
        type: string
        required: true
    secrets:
      kubeconfig:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create kubeconfig
        run: | 
          mkdir -p ~/.kube
          (cat <<EOF
          ${{ secrets.kubeconfig }}
          EOF
          ) > ~/.kube/config
          chmod 0600 ~/.kube/config
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - run: task init
      - name: Deploy # TODO: move this to taskfile
        env:
          HELM_NAMESPACE: ${{ inputs.namespace }}
          HELM_REPOSITORY: ${{ inputs.repository }}
          HELM_CHART: ${{ inputs.chart }}
          HELM_RELEASE: ${{ inputs.release }}
          HELM_VALUES_PATH: ${{ inputs.values_path }}
          COMMIT_SHA: ${{ github.sha }}
        run: task helm:upgrade
