name: build
on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
      app_target:
        type: string
        default: esp32s3
      idf_version:
        type: string
        default: release-v5.3
      workdir:
        type: string
        default: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          cd ${{inputs.workdir}}
          
          cp sdkconfig.${{inputs.app_target}} sdkconfig
          docker run --rm -v $PWD:/project -w /project espressif/idf:${{inputs.idf_version}} idf.py build
          
          APP_VER=$(cat version.txt | head -n 1)
          APP_VER_ALPHA=$(echo $APP_VER | awk -F "." '{print $4}')
          APP_VER=$(echo $APP_VER | awk -F "." '{print $1"."$2"."$3}')
          if [ "${APP_VER_ALPHA}" != "0" ]; then
              APP_VER="${APP_VER}-alpha${APP_VER_ALPHA}"
          fi
          
          mkdir -p ./__release
          cp ./build/${{inputs.app_name}}.bin ./__release/app-${APP_VER}-${{inputs.app_target}}.bin
          cp ./build/bootloader/bootloader.bin ./__release/bootloader-${APP_VER}-${{inputs.app_target}}.bin
      - uses: ncipollo/release-action@v1
        if: ${{github.ref_type == 'tag'}}
        with:
          allowUpdates: true
          artifacts: "${{inputs.app_name}}/__release/*"
