name: build
on:
  workflow_call:
    inputs:
      app_name:
        type: string
        default: ${{ github.event.repository.name }}
      app_version:
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          docker run --rm -v $PWD:/project -w /project espressif/idf:latest idf.py build
