name: build
on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
      app_target:
        type: string
        default: esp32s3
      idf_version:
        type: string
        default: release-v5.3
      workdir:
        type: string
        default: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          docker run --rm -v $PWD/${{inputs.workdir}}:/project -w /project espressif/idf:${{inputs.idf_version}} idf.py set-target ${{inputs.app_target}}
          docker run --rm -v $PWD/${{inputs.workdir}}:/project -w /project espressif/idf:${{inputs.idf_version}} idf.py build
          cp "${{inputs.workdir}}/build/${{inputs.app_name}}.bin" "${{inputs.workdir}}/build/${{inputs.app_name}}-${{inputs.app_target}}.bin"
      - name: Save binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.app_name}}-${{inputs.app_target}}.bin
          path: "${{inputs.workdir}}/build/${{inputs.app_name}}-${{inputs.app_target}}.bin"
          overwrite: true
