name: build
on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
      app_target:
        type: string
        default: esp32s3
      idf_version:
        type: string
        default: release-v5.3
      workdir:
        type: string
        default: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          cp ${{inputs.workdir}}/sdkconfig.${{inputs.app_target}} ${{inputs.workdir}}/sdkconfig
          docker run --rm -v $PWD/${{inputs.workdir}}:/project -w /project espressif/idf:${{inputs.idf_version}} idf.py build
          
          APP_VER=$(cat ${{inputs.workdir}}/version.txt | head -n 1)
          APP_VER_ALPHA=$(echo $APP_VER | awk -F "." '{print $4}')
          if [ "${APP_VER_ALPHA}" != "0" ]; then
              APP_VER="${APP_VER}-alpha${APP_VER_ALPHA}"
          fi
          
          mkdir -p ${{inputs.workdir}}/__release
          cp ${{inputs.workdir}}/build/${{inputs.app_name}}.bin ${{inputs.workdir}}/__release/app-${APP_VER}-${{inputs.app_target}}.bin
          cp ${{inputs.workdir}}/build/bootloader/bootloader.bin ${{inputs.workdir}}/__release/bootloader-${APP_VER}-${{inputs.app_target}}.bin
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ${{inputs.workdir}}/__release/
          overwrite: true
