name: go-app
on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
      app_version:
        type: string
        required: true
      registry_user:
        type: string
        required: false
    secrets:
      registry_password:
        required: false

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - uses: ashep/go-ci/actions/setup-golangci-lint@v1
      - run: task init
      - run: task lint:golangci

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version-file: go.mod
      - run: go mod vendor
      - run: task init
      - run: task test:unit

  func-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - run: go mod vendor
      - run: task init
      - run: task test:func

  build-image:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - func-tests
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - run: task init
      - uses: ashep/go-ci/actions/build-image@v1
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}

  push-image:
    runs-on: ubuntu-latest
    if: ${{ inputs.registry_user != '' }}
    needs:
      - build-image
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ inputs.registry_user }}
          password: ${{ secrets.registry_password }}
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - run: task init
      - uses: ashep/go-ci/actions/push-image@v1
        if: github.ref_name == 'main'
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}
          registry_user: ${{ inputs.registry_user }}
          tag_name: latest
      - uses: ashep/go-ci/actions/push-image@v1
        if: github.ref_name != 'main'
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}
          registry_user: ${{ inputs.registry_user }}
          tag_name: dev
      - uses: ashep/go-ci/actions/push-image@v1
        if: github.ref_type == 'tag'
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}
          registry_user: ${{ inputs.registry_user }}
          tag_name: ${{ github.ref_name }}
