name: build
on:
  workflow_call:
    inputs:
      app_name:
        type: string
        default: ${{ github.event.repository.name }}
      app_version:
        type: string
        default: ${{ github.ref_name }}
      dockerfile:
        type: string
        default: .ci/go/Dockerfile
      go_version:
        type: string
        default: 1.22
      go_private:
        type: string
      registry_host:
        type: string
      registry_user:
        type: string
    secrets:
      private_key:
        required: false
      registry_password:
        required: false

jobs:
  image:
    runs-on: ubuntu-latest
    if: ${{ inputs.registry_user != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ashep/ci
          ref: v1
          path: .ci
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      - uses: ashep/ci/actions/go-private@v1
        with:
          go_private: ${{ inputs.go_private }}
          private_key: ${{ secrets.private_key }}
      - shell: sh
        run: go mod vendor
      - shell: sh
        run: go build -tags osusergo,netgo -ldflags="-extldflags=-static -w -s -X 'github.com/ashep/go-apprun.appName=${{ inputs.app_name }}' -X 'github.com/ashep/go-apprun.appVer=${{ inputs.app_version }}'" -o app.out main.go
      - uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry_host }}
          username: ${{ inputs.registry_user }}
          password: ${{ secrets.registry_password }}
      - uses: ashep/ci/actions/build-image@v1
        if: github.ref_name == 'main'
        with:
          app_name: ${{ inputs.app_name }}
          dockerfile: ${{ inputs.dockerfile }}
          registry_host: ${{ inputs.registry_host }}
          registry_user: ${{ inputs.registry_user }}
          tag_name: latest
      - uses: ashep/ci/actions/build-image@v1
        if: github.ref_name != 'main'
        with:
          app_name: ${{ inputs.app_name }}
          dockerfile: ${{ inputs.dockerfile }}
          registry_host: ${{ inputs.registry_host }}
          registry_user: ${{ inputs.registry_user }}
          tag_name: dev
      - uses: ashep/ci/actions/build-image@v1
        if: github.ref_type == 'tag'
        with:
          app_name: ${{ inputs.app_name }}
          dockerfile: ${{ inputs.dockerfile }}
          registry_host: ${{ inputs.registry_host }}
          registry_user: ${{ inputs.registry_user }}
          tag_name: ${{ github.ref_name }}
