name: test
on:
  workflow_call:
    inputs:
      go_version:
        type: string
        default: 1.22
      go_private:
        type: string
    secrets:
      private_key:
        required: false

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      - uses: ashep/go-ci/actions/go-private@v1
        with:
          go_private: ${{ inputs.go_private }}
          private_key: ${{ secrets.private_key }}
      - run: go mod vendor
      - run: go test -race ./...

  func:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      - uses: ashep/go-ci/actions/go-private@v1
        with:
          go_private: ${{ inputs.go_private }}
          private_key: ${{ secrets.private_key }}
      - run: go mod vendor
      - run: |
          if [ -f docker-compose.tests.yaml ];
            then docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml up --remove-orphans -d
            docker compose -p {{.APP_NAME}}_tests -f docker-compose.tests.yaml run --rm --remove-orphans tests go test -v -mod=vendor -tags=functest ./tests/...
          fi
