name: test
on:
  workflow_call:
    inputs:
      go_version:
        type: string
        default: 1.26.7
      go_private:
        type: string
      dotenv:
        type: string
        required: false
    secrets:
      private_key:
        required: false
      dotenv:
        required: false

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      - name: Set up go-private
        uses: ashep/ci/actions/go-private@v1
        with:
          go_private: ${{ inputs.go_private }}
          private_key: ${{ secrets.private_key }}
      - name: Vendoring
        run: go mod vendor
      - name: Add .env variables
        run: |
          (cat <<'EOF'
          ${{ inputs.dotenv }}
          EOF
          ) >> ${{ inputs.workdir }}/.env

          (cat <<'EOF'
          ${{ secrets.dotenv }}
          EOF
          ) >> ${{ inputs.workdir }}/.env
      - name: Run unit tests
        run: go test -v -mod=vendor -race ./...

  func:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      - name: Set up go-private
        uses: ashep/ci/actions/go-private@v1
        with:
          go_private: ${{ inputs.go_private }}
          private_key: ${{ secrets.private_key }}
      - name: Vendoring
        run: go mod vendor
      - name: Add .env variables
        run: |
          (cat <<'EOF'
          ${{ inputs.dotenv }}
          EOF
          ) >> ${{ inputs.workdir }}/.env

          (cat <<'EOF'
          ${{ secrets.dotenv }}
          EOF
          ) >> ${{ inputs.workdir }}/.env
      - name: Run func tests
        run: |
          if [ -f docker-compose.tests.yaml ]; then
            docker compose -f docker-compose.tests.yaml up --remove-orphans -d
            docker compose -f docker-compose.tests.yaml run --rm --remove-orphans tests go test -v -mod=vendor -tags=functest ./tests/...
          fi
