name: publish-release.yml
on:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: release-*
          merge-multiple: true
          path: ./release
      - uses: ncipollo/release-action@v1
        if: ${{ github.ref_type == 'tag' }}
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ./release/*
          generateReleaseNotes: true
          makeLatest: ${{ !contains(github.ref_name, '-alpha') }}
          prerelease: ${{ contains(github.ref_name, '-alpha') }}
          removeArtifacts: true
          replacesArtifacts: true
